name:  Informe de bug
description: Describe el error ocurrido, qu茅 versi贸n de Mega usas y c贸mo podemos reproducirlo.
title: "[BUG]"
labels: Bug
body:
  - type: textarea
    id: resumen
    attributes:
      label: 驴Qu茅 est谩 pasando?
      description: Describe con detalle el bug y qu茅 esperabas que ocurriera. Adjunta capturas si se puede.
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducirlo
      description: Enumera los pasos exactos para que otro ingeniero reproduzca el problema.
      placeholder: |
        1. Entr茅 a Mega y ...
        2. Con esta configuraci贸n ...
        3. Ejecut茅 ...
        4. Obtuve este error ...
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Comportamiento esperado
      description: Qu茅 esperabas que sucediera en lugar del error.
  - type: input
    id: mega_version
    attributes:
      label: Versi贸n de Mega
      description: Indica la versi贸n exacta.
      placeholder: sendingtk/chatwoot:v4.9.0, etc.
    validations:
      required: true
  - type: dropdown
    id: entorno
    attributes:
      label: Entorno
      description: 驴Usas Mega Cloud (mega.cloud.com) o una instancia autoalojada? Describe el tipo de despliegue si es propio.
      options:
        - Mega Cloud (mega.cloud.com)
        - VM Linux
        - Docker
        - Kubernetes
        - Heroku
        - Otro (especifica en contexto adicional)
    validations:
      required: true
  - type: dropdown
    id: plataforma
    attributes:
      label: Plataforma
      description: D贸nde ocurre el bug.
      options:
        - Navegador
        - M贸vil
        - Escritorio
  - type: input
    id: sistema_operativo
    attributes:
      label: Sistema operativo
      description: Indica el sistema operativo y versi贸n que est谩s usando.
  - type: input
    id: navegador
    attributes:
      label: Navegador y versi贸n
      description: Nombre y versi贸n del navegador donde aparece el bug.
  - type: textarea
    id: context_info
    attributes:
      label: Contexto adicional
      description: Informaci贸n adicional, logs, comandos (`mega status`, `mega check`) o configuraciones que puedan ayudar.
